# argument image instead of bui'ld**?
# https://docs.docker.com/compose/compose-file/#image
# -- Author: Christopher Ek and Lukas Eklund -- #
# -- Version: 1.12.1 ---------------------------#
# -- Date: 2020-09-10 --------------------------#
# -- License: MIT ------------------------------#


# All Services, database, web, worker
services:

  # Database
  database:
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    build:
      # Where to find the source code
      context: ./database
      # Dockerfile name.
      dockerfile: Dockerfile
    # Ports
    ports:
      - "5432:5432"
      -
  # Web
  website:
    # How this service is built
    build:
      # Where the source code is
      context: ./website
      # Dockerfile name
      dockerfile: Dockerfile
    # Ports
    ports:
      - "5000:5000"

  # Worker
  worker:
    # How this service will build
    build:
      # Where the source code is
      context: ./worker
      # Dockerfile name
      dockerfile: Dockerfile
    # if database fails, do not turn on.
    depends_on:
      - database

volumes:
  dbdata:
